DROP TABLE IF EXISTS favorite_mon;
DROP TABLE IF EXISTS seen;
DROP TABLE IF EXISTS caught;

CREATE TABLE favorite_mon (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
sprite TEXT NOT NULL,
name TEXT NOT NULL,
primary_type TEXT NOT NULL,
secondary_type TEXT
);

CREATE TABLE seen (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
sprite TEXT NOT NULL,
name TEXT NOT NULL,
primary_type TEXT NOT NULL,
secondary_type TEXT
);

CREATE TABLE caught (
id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
sprite TEXT NOT NULL,
name TEXT NOT NULL,
primary_type TEXT NOT NULL,
secondary_type TEXT
);